Создать ViewModel
apmath-web/expenses pull request #20
Opened 2019-03-29 11:13 UTC by TimurSirkin

- [ ] Создать структуру для хранения данных
- [ ] Создать методы заполнения полей структуры
- [ ] Создать методы валидации

close #7

2019-03-29 14:57 UTC, levozavr commented
@TimurSirkin не стоит запрашивать ревью до того как задача завершена, так как оповещение об этом уйдет вниз и будет не удобно.
[Как быть хорошим контрибьютором](https://habr.com/ru/company/sberbank/blog/445440/)

2019-03-29 17:13 UTC, TimurSirkin commented
> @TimurSirkin не стоит запрашивать ревью до того как задача завершена, так как оповещение об этом уйдет вниз и будет не удобно.
> [Как быть хорошим контрибьютором](https://habr.com/ru/company/sberbank/blog/445440/)

Убрал

2019-03-29 17:56 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +	//Тут такой джейсон???
По идее должен быть таким, но у вас в  [спецификации](https://docs.google.com/document/d/1RiURQhXa6QD7rrq4720uTNWcksZWoBAFmj54RSLcgUg/edit#heading=h.b1787skcu2t) немного другой, так что стоит определится, где правильный

2019-03-29 18:00 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +	CoborrowersIdSlice []int `json:"CoBorrowersIds"`
Еще json тэги стоит именовать с маленькой буквы, так как в спецификации вроде везде идет lower camel case для нэйминга полей.
      \`json:"coBorrowersIds"\``

2019-03-29 18:02 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +	//Тут как поключить валдиацию???
Можно написать:
```suggestion
	validator ValidationInterface
```

2019-03-29 18:03 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +		}
Тут скобки надо правильно закомментировать, иначе будет ошибка компиляции.

на этой и на следующей строке

2019-03-29 18:05 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +//func (idsViewModel *IdsViewModel) GetValidation() Domain.ValidationInterface { Это для чего?
это для получения **validator** из модели, его **getter**

2019-03-29 18:06 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +func (idsViewModel *IdsViewModel) MarshalJSON() (b []byte, e error) { //Тута так?
Эта функция для модели id'шников вам не нужна, вам не надо их приводить к json, вам надо наоборот из json получать id

2019-03-29 18:06 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +	tmpClient := JsonIds{}
А чего переменные со странными именами?

2019-03-29 18:07 UTC, levozavr commented on Application/viewModels/IdListViewModel.go
> +//func (idsViewModel *IdsViewModel) Hydrate(client Domain.viewModelInreface) { Тут что должно быть???
Можно смело удалять у вас нет гидрации domain модели к этой view model

2019-03-29 19:22 UTC, levkovalenko requested changes

2019-03-29 19:22 UTC, levkovalenko commented on Application/viewModels/IdListViewModel.go
> +	tmpClient := JsonIds{}
Почему tmpClient?

2019-03-29 19:22 UTC, levkovalenko commented on Application/Validation/Validation.go
> +type Validation struct {
Почему не имплементирован весь интерфейс?

2019-03-30 07:04 UTC, TimurSirkin commented on Application/viewModels/IdListViewModel.go
> +	tmpClient := JsonIds{}
Исправил

2019-03-30 07:04 UTC, TimurSirkin commented on Application/Validation/Validation.go
> +type Validation struct {
Имплементировал

2019-03-30 07:32 UTC, levkovalenko approved these changes

2019-03-30 07:32 UTC, merged