Create basic interface
apmath-web/expenses pull request #25
Opened 2019-03-30 07:56 UTC by morozzArt

2019-03-30 07:57 UTC, TimurSirkin commented
А ГДЕ ОПИСАНИЕ!!!

2019-03-30 07:57 UTC, TimurSirkin commented
БЫДЛОКОДЕР

2019-03-30 07:57 UTC, TimurSirkin commented
ИНТЕРФЕЙС ДЛЯ ДИБИЛОВ

2019-04-05 11:54 UTC, morozzArt commented
@levozavr Review please

2019-04-05 18:53 UTC, levkovalenko requested changes
А где интерфейс сервиса?

2019-04-05 18:53 UTC, levozavr commented on Domain/domainModelInterfaces.go
> +type HelloWorldApplicationModel interface {
Это что?

2019-04-05 18:53 UTC, levozavr commented on Domain/domainModelInterfaces.go
> +type PersonDomainModelInterface interface {
вроде говорили о двух доменных моделях Person и Ids?

2019-04-05 18:53 UTC, levozavr commented on Domain/repositoriesInterface.go
> +type ExpensesRepositoryInterface interface {
А почему остался предыдущий интерфес?

2019-04-05 19:28 UTC, morozzArt commented on Domain/domainModelInterfaces.go
> +type HelloWorldApplicationModel interface {
Для интерфейса сервиса отдельный issue есть

2019-04-05 19:32 UTC, morozzArt commented on Domain/domainModelInterfaces.go
> +type HelloWorldApplicationModel interface {
Это чтобы не вносить изменения в файлы репозитория, так как данный issue не требует этого

2019-04-05 19:32 UTC, morozzArt commented on Domain/domainModelInterfaces.go
> +type PersonDomainModelInterface interface {
Для доменной модели Ids есть отдельный issue

2019-04-05 19:32 UTC, morozzArt commented on Domain/repositoriesInterface.go
> +type ExpensesRepositoryInterface interface {
см.выше

2019-04-06 06:49 UTC, levozavr commented on Domain/domainModelInterfaces.go
> +type HelloWorldApplicationModel interface {
@morozzArt добавь на это задачу

2019-04-07 13:54 UTC, levkovalenko approved these changes

2019-04-07 13:54 UTC, merged