Создать person domain model
apmath-web/expenses pull request #27
Opened 2019-04-11 13:43 UTC by morozzArt

- [ ]  Создать объект
- [ ]  Создать getter's
- [ ]  Создать mapper
- [ ]  Реализовать метод calculate

close: #14

2019-04-11 19:44 UTC, morozzArt commented
Review please @levozavr

2019-04-11 19:51 UTC, levkovalenko requested changes

2019-04-11 19:51 UTC, levozavr commented on Domain/Models/PersonDomainModel.go
> +	return person.FirstName
```suggestion
	return person.LastName
```

2019-04-11 19:51 UTC, levozavr commented on Infrastructure/applicationModels/JobApplicationModel.go
> +}
```suggestion
}

```

2019-04-11 19:51 UTC, levozavr commented on Infrastructure/applicationModels/PersonApplicationModel.go
> +}
```suggestion
}

```

2019-04-11 19:51 UTC, levozavr commented on Infrastructure/Mapper/PersonMapper.go
> +func SumWageJob (jobs []applicationModels.JobApplicationModel) int {
Это стоит сделать внутренней функцией PersonApplicationModel

2019-04-11 19:51 UTC, levozavr commented on Domain/Models/PersonDomainModel.go
> +	MaxValue = float64(SumWagePerson) / float64(len(persons))
стоит округлить на мой взгляд, хотя бы до сотых

2019-04-12 09:53 UTC, morozzArt commented on Infrastructure/applicationModels/JobApplicationModel.go
> +}
?

2019-04-12 09:53 UTC, morozzArt commented on Infrastructure/applicationModels/PersonApplicationModel.go
> +}
?

2019-04-12 10:05 UTC, morozzArt commented on Domain/Models/PersonDomainModel.go
> +	MaxValue = float64(SumWagePerson) / float64(len(persons))
Исправил @levozavr

2019-04-12 10:05 UTC, morozzArt commented on Infrastructure/Mapper/PersonMapper.go
> +func SumWageJob (jobs []applicationModels.JobApplicationModel) int {
Исправил @levozavr

2019-04-12 10:53 UTC, levozavr commented on Infrastructure/applicationModels/PersonApplicationModel.go
> +}
пустые строки в конце файла

2019-04-21 01:36 UTC, levozavr commented on Domain/domainModelInterfaces.go
> +}
```suggestion
}

```

2019-04-27 08:24 UTC, levkovalenko submitted a review, later dismissed

2019-04-27 08:28 UTC, levkovalenko approved these changes

2019-04-27 08:30 UTC, merged