Создать action
apmath-web/expenses pull request #34
Opened 2019-05-20 20:01 UTC by TimurSirkin

- [ ] Получить данные
- [ ] Провалидировать
- [ ] Вызвать метод расчета
- [ ] Вернуть данные

close #8

2019-05-20 21:24 UTC, TimurSirkin commented
После создания ExpensesViewModel вылезает варнинг **Unexported field with tag**
Ругается на вот это **amount float64 `json:"maxPayment"`**

2019-05-20 21:47 UTC, TimurSirkin commented
В функции GetExpenses в actionGetExpenses я получаю тело запроса через **c.BindJSON(&vm)**
При этом я получу так же и параметр из URL (clientId) или мне нужно его явно получить через **c.Param("clientId")**?

2019-05-21 15:44 UTC, levkovalenko requested changes

2019-05-21 15:44 UTC, levozavr commented on Application/viewModels/ExpensesViewModel.go
> +func (expensesViewModel *ExpensesViewModel) Validate() bool {
Валидация нужна только если модель строится из json, тут она лишняя

2019-05-21 15:44 UTC, levozavr commented on Application/actions/actionGetExpenses.go
> +		validator.AddMessage(Validation.GenMessage("clientId", err.Error()))
тут у тебя ошибка может быть только в формате JSON, а не определенного поля

2019-05-21 15:44 UTC, levozavr commented on Application/actions/actionGetExpenses.go
> +		validator.SetMessage("validation error")
тут у тебя не валидационная ошибка

2019-05-21 15:44 UTC, levozavr commented on Application/actions/actionGetExpenses.go
> +	if err != nil {
как у тебя обрабатываются различные исключения:
clients недоступен?
clients вернул ошибку 404, так как какого-то пользователя нет?
clients вкрнул 400 из-за неверного оформления запроса?
своя нутрення ошибка при переполнении каких-то типов данных?

2019-05-21 18:21 UTC, levkovalenko approved these changes

2019-05-21 18:21 UTC, merged