test clientFetchServise URL
apmath-web/expenses pull request #43
Opened 2019-05-24 22:10 UTC by varlogen

- [ ] test clientFetchServise URL
close #42

2019-05-25 09:04 UTC, levozavr commented
PR for @malinink

2019-05-26 19:43 UTC, malinink requested changes

2019-05-26 19:43 UTC, malinink commented on Infrastructure/ClientFetchServiceUrl_test.go
> +	if url != "http://0.0.0.0:8080/v1/" {
вы же только 1 метод проверили, а проверить сам сервис?

2019-05-26 19:52 UTC, varlogen commented on Infrastructure/ClientFetchServiceUrl_test.go
> +	if url != "http://0.0.0.0:8080/v1/" {
это же надо проверять в dockerе с поднятым сервисом client

2019-05-26 20:14 UTC, levozavr commented on Infrastructure/ClientFetchServiceUrl_test.go
> +	if url != "http://0.0.0.0:8080/v1/" {
@varlogen надо писать для этого мок

2019-06-01 08:27 UTC, closed without merging