Upadate validation
apmath-web/expenses pull request #50
Opened 2019-05-30 14:55 UTC by TimurSirkin

Add checking on negative client's ID
Add checking on client's ID and coborrower's ID eqauling
Add checking on coborrower's equal IDs
Add showing invalid ID in error message

close #49

2019-05-30 20:32 UTC, malinink requested changes

2019-05-30 20:32 UTC, malinink commented on Application/viewModels/IdListViewModel.go
> +		for _, firstId := range idsViewModel.CoborrowersIdSlice {
дык вроде как уже гдк-то я видел нормальную проверку на уникальность?

2019-05-30 20:32 UTC, malinink commented on Application/viewModels/IdListViewModel.go
> +		for _, firstId := range idsViewModel.CoborrowersIdSlice {
зачем изобретать велосипед?

2019-05-30 20:49 UTC, TimurSirkin commented on Application/viewModels/IdListViewModel.go
> +		for _, firstId := range idsViewModel.CoborrowersIdSlice {
Гугл сказал, что нету в Go функции contains

2019-05-31 10:49 UTC, malinink commented on Application/viewModels/IdListViewModel.go
> +		for _, firstId := range idsViewModel.CoborrowersIdSlice {
http://www.golangprograms.com/remove-duplicate-values-from-slice.html

2019-05-31 14:36 UTC, TimurSirkin commented on Application/viewModels/IdListViewModel.go
> +		for _, firstId := range idsViewModel.CoborrowersIdSlice {
Изменил

2019-05-31 19:01 UTC, malinink approved these changes

2019-05-31 19:02 UTC, merged